// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Angara.Chart")>]
[<assembly: AssemblyProductAttribute("Angara.Chart")>]
[<assembly: AssemblyDescriptionAttribute("Data visualization library for F#.")>]
[<assembly: AssemblyVersionAttribute("0.2.4")>]
[<assembly: AssemblyFileVersionAttribute("0.2.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Angara.Chart"
    let [<Literal>] AssemblyProduct = "Angara.Chart"
    let [<Literal>] AssemblyDescription = "Data visualization library for F#."
    let [<Literal>] AssemblyVersion = "0.2.4"
    let [<Literal>] AssemblyFileVersion = "0.2.4"
